apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tpv-primecolada
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/launch-stage: GA
        run.googleapis.com/allow-unauthenticated: "true"
    spec:
      containers:
        - name: frontend
          image: gcr.io/tpv-primecolada/primecolada-frontend:latest
          env:
            - name: BACKEND_HOST
              value: localhost
            - name: BACKEND_PORT
              value: "5000"
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
        - name: backend
          image: gcr.io/tpv-primecolada/primecolada-backend:latest
          env:
            - name: FLASK_ENV
              value: production
            - name: BACKEND_HOST
              value: localhost
            - name: BACKEND_PORT
              value: "5000"
        # - name: websockets
        #   image: gcr.io/tpv-primecolada/primecolada-websockets:latest
        #   env:
        #     - name: BACKEND_HOST
        #       value: localhost
        #     - name: BACKEND_PORT
        #       value: "5000"
      serviceAccountName: 15318690559-compute@developer.gserviceaccount.com
  traffic:
    - latestRevision: true
      percent: 100